services:
  app:
    container_name: container-landingpage-financial-tracker
    build:
      context: .
      dockerfile: Dockerfile.mounted
    ports:
      - "3000:3000" # Mapea puerto 3000 (host) â†’ 3000 (contenedor)
    environment:
      - BACKEND_URL=http://backend-api:80/api
      - NODE_ENV=development
    networks:
      - development
    volumes:
      - .:/app
      - /app/node_modules # Para evitar conflictos con node_modules local
networks:
  development:
    external: true
