services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: financial-tracker-backend
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - development
      - financial_tracker_net_backend
    depends_on:
      - postgres
    environment:
      - DB_HOST=financial-tracker-db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    image: postgres:17.6
    container_name: financial-tracker-db
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=${DB_USERNAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_DATABASE}
    networks:
    - financial_tracker_net_backend
    volumes:
      - financial_tracker_data:/var/lib/postgresql/data

volumes:
  financial_tracker_data:

networks:
  development:
    external: true
  financial_tracker_net_backend:
    driver: bridge
    external: false